syntax = "proto3";

package app.morphe.extension.youtube.innertube;

option optimize_for = LITE_RUNTIME;
option java_package = "app.morphe.extension.youtube.innertube";

message Icon {
    YTIconType ytIconType = 1;
}

enum YTIconType {
    UNKNOWN = 0;
    SEARCH = 60;
    FAB_CAMERA = 141;
    VIDEO_CAMERA = 295;
    CREATION_ENTRY = 405;
    PIVOT_HOME = 406;
    CREATION_ENTRY_V2 = 650;
    CREATION_ENTRY_UPLOAD_ICON = 670;
    SEARCH_BOLD = 1045;
    TAB_HOME_CAIRO = 1154;
    SEARCH_CAIRO = 1160;
    SETTINGS_CAIRO = 1162;
}
