syntax = "proto3";

import "app/morphe/extension/shared/innertube/response_context.proto";

package app.morphe.extension.shared.innertube;

option optimize_for = LITE_RUNTIME;
option java_package = "app.morphe.extension.shared.innertube";

message PlayerResponse {
  optional ResponseContext responseContext = 1;
  optional PlayabilityStatus playabilityStatus = 2;
  optional StreamingData streamingData = 4;
  optional PlayerConfig playerConfig = 15;
}

message PlayabilityStatus {
  optional Status status = 1;
  optional string reason = 2;
}

enum Status {
  OK = 0;
  ERROR = 1;
  UNPLAYABLE = 2;
  LOGIN_REQUIRED = 3;
  CONTENT_CHECK_REQUIRED = 4;
  AGE_CHECK_REQUIRED = 5;
  LIVE_STREAM_OFFLINE = 6;
  FULLSCREEN_ONLY = 7;
  GL_PLAYBACK_REQUIRED = 8;
  AGE_VERIFICATION_REQUIRED = 9;
}

message StreamingData {
  repeated Format formats = 2;
  repeated Format adaptiveFormats = 3;
  optional string serverAbrStreamingUrl = 15;
}

message Format {
  optional string url = 2;
  optional string signatureCipher = 48;
}

message PlayerConfig {
}
