package app.revanced.patches.youtube.utils.mainactivity

import app.revanced.patches.shared.mainactivity.BaseMainActivityResolvePatch
import app.revanced.patches.youtube.utils.mainactivity.fingerprints.MainActivityFingerprint

object MainActivityResolvePatch : BaseMainActivityResolvePatch(MainActivityFingerprint)