version: @Mystic_realm___666
updates: @Mystic_realm___666  
  - package-ecosystem: npm   directory: /
    target-branch: dev
    schedgithub-actionserval: monthly

package-ecosystem:tem: npm
    lschedule:ctory: /
/nch: de[]    schedule:
      interv: :mpackage-ecosystem:-ecosyst: youtube/premium
    labels: []
    directdirectory:ch: dev
    schedule: 
    onetime: hly
