package app.morphe.patches.reddit.utils.fix.signature

import app.morphe.patches.all.misc.signature.AppInfo
import app.morphe.patches.all.misc.signature.baseSpoofSignaturePatch

val spoofSignaturePatch = baseSpoofSignaturePatch {
    AppInfo(
        packageName = "com.reddit.frontpage",
        certificateData = "MIIDWzCCAkOgAwIBAgIEVA7dvDANBgkqhkiG9w0BAQsFADBeMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDVNhbiBGcmFuY2lzY28xFDASBgNVBAoTC3JlZGRpdCBJbmMuMRQwEgYDVQQDEwtNb2JpbGUgQXBwczAeFw0xNDAzMDEwMDMxMTJaFw0zOTAyMjMwMDMxMTJaMF4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNU2FuIEZyYW5jaXNjbzEUMBIGA1UEChMLcmVkZGl0IEluYy4xFDASBgNVBAMTC01vYmlsZSBBcHBzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxIOFo/qVmYq3S4ZKNMSMT9UjU0kZQDDThODZM5o1q3NlIlX2XOP/BNP/kCT4Xww69frbKj6Izd2jn/xOvA+JMqdEFjlRWoF7poJzdKA2zw3L814pzZUhIF1IIoUJ6YiHOkU4hiqvdn/VjRTB5rIgw0bs9NoEIYynp3qcVwCuEU2TyEy4F9aUU1YsfejUWd3GoWH2dZqu+Hg5yJKWBpWAWjOEK1f2ltc+JtGLl9AReDsfTYBxBobqZCK4yKsq65YVL7flp7MkQ/fgcrXWgknUpC6Pb+MKgnK083noS8HNlsUOgW57fJj6mmcebW9fnDpl6FBzxdDerGZ5AxG/yb0B9QIDAQABoyEwHzAdBgNVHQ4EFgQUoq623hlCFRHg6xsCZHTVrgMZ6cswDQYJKoZIhvcNAQELBQADggEBAJR0XZDyZgIqhZPNtz9yn4kdxoUg9d7hRcleSvggJc5OAc3dcIrTXyRf2vkL1KJM+/zTOs0DwNm6rYuQhKDvZ9XtbMllkn2yykjs/xR/4BXqhyQp8sOVr5wRatG6aIbVJ52hldNHY352EgWYLwvz0L7GNcSB+vO3eIkbgdavFgnQWaoVyfoWB0bqky7079hfXHMRPyiZ0ZLwwApqHjDZSaU4gbgjrx5ni8BzchHerwxjsE4yLamkUTZ5/SHpIsJv9ychDwpLbguYRGTyiWNwRZoRurFqdGatHAh0OAr5E9IXNi9EoKksC2RjatfMllQETns7PDbxQ1/tB8DExpyB71U=",
    )
}